services:
  nike:
      image: ghcr.io/m6o4solutions/nike-web-project:latest
      container_name: nike
      restart: unless-stopped
      networks:
        - traefik-network
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nike.rule=Host(`nike.m6o4solutions.com`)"
        - "traefik.http.routers.nike.entrypoints=websecure"
        - "traefik.http.routers.nike.tls.certresolver=letsencrypt"
        - "traefik.http.services.nike.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true